-- 1. LIMPIEZA DE TABLAS
BEGIN
   FOR t IN (SELECT table_name FROM user_tables WHERE table_name IN (
      'ARTICLE_CATEGORIES', 'ARTICLE_TAGS', 'COMMENTS', 'ARTICLES', 'CATEGORIES', 'TAGS', 'USERS'
   )) LOOP
      EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
   END LOOP;
END;
/

-- 2. TABLAS BASE
CREATE TABLE users (
    user_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR2(100) NOT NULL,
    email       VARCHAR2(150) NOT NULL UNIQUE
)
/

CREATE TABLE tags (
    tag_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR2(50) NOT NULL UNIQUE,
    url         VARCHAR2(255)
)
/

CREATE TABLE categories (
    category_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR2(50) NOT NULL UNIQUE,
    url         VARCHAR2(255)
)
/

CREATE TABLE articles (
    article_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     NUMBER NOT NULL,
    title       VARCHAR2(200) NOT NULL,
    published_date DATE DEFAULT SYSDATE NOT NULL,
    article_text CLOB NOT NULL,
    status      VARCHAR2(10) DEFAULT 'ACTIVO' NOT NULL,
    CONSTRAINT fk_articles_users FOREIGN KEY (user_id) 
        REFERENCES users(user_id) ON DELETE CASCADE
)
/

CREATE TABLE comments (
    comment_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id  NUMBER NOT NULL,
    user_id     NUMBER,
    name        VARCHAR2(100) NOT NULL,
    url         VARCHAR2(255),
    comment_text VARCHAR2(1000) NOT NULL,
    CONSTRAINT fk_comments_articles FOREIGN KEY (article_id) 
        REFERENCES articles(article_id) ON DELETE CASCADE,
    CONSTRAINT fk_comments_users FOREIGN KEY (user_id) 
        REFERENCES users(user_id) ON DELETE SET NULL
)
/

CREATE TABLE article_tags (
    article_id  NUMBER NOT NULL,
    tag_id      NUMBER NOT NULL,
    CONSTRAINT pk_article_tags PRIMARY KEY (article_id, tag_id),
    CONSTRAINT fk_at_articles FOREIGN KEY (article_id) 
        REFERENCES articles(article_id) ON DELETE CASCADE,
    CONSTRAINT fk_at_tags FOREIGN KEY (tag_id) 
        REFERENCES tags(tag_id) ON DELETE CASCADE
)
/

CREATE TABLE article_categories (
    article_id  NUMBER NOT NULL,
    category_id NUMBER NOT NULL,
    CONSTRAINT pk_article_categories PRIMARY KEY (article_id, category_id),
    CONSTRAINT fk_ac_articles FOREIGN KEY (article_id) 
        REFERENCES articles(article_id) ON DELETE CASCADE,
    CONSTRAINT fk_ac_categories FOREIGN KEY (category_id) 
        REFERENCES categories(category_id) ON DELETE CASCADE
)
/

-- 3. PROCEDIMIENTOS Y FUNCIONES PL/SQL
CREATE OR REPLACE PROCEDURE sp_guardar_usuario (
    p_name  IN users.name%TYPE,
    p_email IN users.email%TYPE,
    p_id    OUT users.user_id%TYPE
) IS
BEGIN
    INSERT INTO users (name, email)
    VALUES (p_name, p_email)
    RETURNING user_id INTO p_id;
    COMMIT;
END sp_guardar_usuario;
/

CREATE OR REPLACE PROCEDURE sp_crear_articulo (
    p_user_id IN articles.user_id%TYPE,
    p_title   IN articles.title%TYPE,
    p_text    IN articles.article_text%TYPE,
    p_id      OUT articles.article_id%TYPE
) IS
BEGIN
    INSERT INTO articles (user_id, title, article_text, status)
    VALUES (p_user_id, p_title, p_text, 'ACTIVO')
    RETURNING article_id INTO p_id;
    COMMIT;
END sp_crear_articulo;
/

CREATE OR REPLACE PROCEDURE sp_eliminar_articulo_logico (
    p_article_id IN articles.article_id%TYPE
) IS
BEGIN
    UPDATE articles
    SET status = 'INACTIVO'
    WHERE article_id = p_article_id;
    COMMIT;
END sp_eliminar_articulo_logico;
/

CREATE OR REPLACE PROCEDURE sp_agregar_comentario (
    p_article_id IN comments.article_id%TYPE,
    p_user_id    IN comments.user_id%TYPE,
    p_name       IN comments.name%TYPE,
    p_url        IN comments.url%TYPE,
    p_text       IN comments.comment_text%TYPE
) IS
BEGIN
    INSERT INTO comments (article_id, user_id, name, url, comment_text)
    VALUES (p_article_id, p_user_id, p_name, p_url, p_text);
    COMMIT;
END sp_agregar_comentario;
/

CREATE OR REPLACE FUNCTION fn_total_comentarios (
    p_article_id IN comments.article_id%TYPE
) RETURN NUMBER IS
    v_total NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_total
    FROM comments
    WHERE article_id = p_article_id;
    
    RETURN v_total;
END fn_total_comentarios;
/

CREATE OR REPLACE PROCEDURE sp_listar_articulos (
    p_cursor OUT SYS_REFCURSOR
) IS
BEGIN
    OPEN p_cursor FOR
        SELECT a.article_id, 
               a.title, 
               u.name AS autor, 
               TO_CHAR(a.published_date, 'YYYY-MM-DD HH24:MI') AS fecha, 
               DBMS_LOB.SUBSTR(a.article_text, 4000, 1) AS texto,
               fn_total_comentarios(a.article_id) AS num_comentarios
        FROM articles a
        JOIN users u ON a.user_id = u.user_id
        WHERE a.status = 'ACTIVO'
        ORDER BY a.published_date DESC;
END sp_listar_articulos;
/

CREATE OR REPLACE PROCEDURE sp_asignar_tag (
    p_article_id IN article_tags.article_id%TYPE,
    p_name       IN tags.name%TYPE,
    p_url        IN tags.url%TYPE DEFAULT NULL
) IS
    v_tag_id tags.tag_id%TYPE;
BEGIN
    MERGE INTO tags t
    USING (SELECT p_name AS name FROM dual) s
    ON (t.name = s.name)
    WHEN MATCHED THEN UPDATE SET t.url = NVL(p_url, t.url)
    WHEN NOT MATCHED THEN INSERT (name, url) VALUES (p_name, p_url);

    SELECT tag_id INTO v_tag_id FROM tags WHERE name = p_name;

    MERGE INTO article_tags rel
    USING (SELECT p_article_id AS article_id, v_tag_id AS tag_id FROM dual) s
    ON (rel.article_id = s.article_id AND rel.tag_id = s.tag_id)
    WHEN NOT MATCHED THEN INSERT (article_id, tag_id) VALUES (s.article_id, s.tag_id);
    COMMIT;
END sp_asignar_tag;
/

CREATE OR REPLACE PROCEDURE sp_asignar_categoria (
    p_article_id IN article_categories.article_id%TYPE,
    p_name       IN categories.name%TYPE,
    p_url        IN categories.url%TYPE DEFAULT NULL
) IS
    v_category_id categories.category_id%TYPE;
BEGIN
    MERGE INTO categories c
    USING (SELECT p_name AS name FROM dual) s
    ON (c.name = s.name)
    WHEN MATCHED THEN UPDATE SET c.url = NVL(p_url, c.url)
    WHEN NOT MATCHED THEN INSERT (name, url) VALUES (p_name, p_url);

    SELECT category_id INTO v_category_id FROM categories WHERE name = p_name;

    MERGE INTO article_categories rel
    USING (SELECT p_article_id AS article_id, v_category_id AS category_id FROM dual) s
    ON (rel.article_id = s.article_id AND rel.category_id = s.category_id)
    WHEN NOT MATCHED THEN INSERT (article_id, category_id) VALUES (s.article_id, s.category_id);
    COMMIT;
END sp_asignar_categoria;
/

CREATE OR REPLACE FUNCTION fn_listar_tags (
    p_article_id IN article_tags.article_id%TYPE
) RETURN VARCHAR2 IS
    v_tags VARCHAR2(4000);
BEGIN
    SELECT LISTAGG(t.name, ', ') WITHIN GROUP (ORDER BY t.name)
    INTO v_tags
    FROM article_tags rel
    JOIN tags t ON rel.tag_id = t.tag_id
    WHERE rel.article_id = p_article_id;

    RETURN v_tags;
END fn_listar_tags;
/

CREATE OR REPLACE FUNCTION fn_listar_categorias (
    p_article_id IN article_categories.article_id%TYPE
) RETURN VARCHAR2 IS
    v_categorias VARCHAR2(4000);
BEGIN
    SELECT LISTAGG(c.name, ', ') WITHIN GROUP (ORDER BY c.name)
    INTO v_categorias
    FROM article_categories rel
    JOIN categories c ON rel.category_id = c.category_id
    WHERE rel.article_id = p_article_id;

    RETURN v_categorias;
END fn_listar_categorias;
/